### ISSUE TITLE
ESC max limit

### ISSUE THREAD

**Issue by mkeyno** [aentinger/AntweightElectronicSpeedController#1]
hi , sorry to open ticket for my question , but what is the max current rate of your design ? can it use for much higher amper with just replacing the mosfet to higher grade?

**Comment by aentinger** [comment]
Hi,

Opening a ticket is allright although you could have also dropped me an email via the lxrobotics email address. To answer your question: By replacing with higher rated MOSFETs you get more current BUT: Too high current might vaporize PCB traces, stronger MOSFETs might draw more current than the microcontroller can provide and you might be in need of dedicated MOSFET gate drivers. I suggest reading up on some design guidelines. Of course it all depends on how much more current you need. As for the current rate of the design - 1A continous @ 12 V @ room temperature. 

Cheers, Alex
